# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klvr', '0002_auto_20170101_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.CharField(max_length=1000),
        ),
    ]
