# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klvr', '0012_auto_20170103_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
    ]
