# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klvr', '0015_remove_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='klvr.Tag'),
        ),
    ]
