# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 02:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('klvr', '0016_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workers',
            field=models.ManyToManyField(related_name='task_workers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
